### ISSUE TITLE
Training for KITTI

### ISSUE THREAD

**Issue by anupamsobti** [likesum/prdepth#1]
Hi

Great job on this paper! I'm trying to train the model for the KITTI dataset. Is there a standard conversion for the caffemodel DORN weights to the npz format you've used? Also, can you share how long I should expect the training to take?

Thanks!

**Comment by likesum** [comment]
Sorry I don't have a standard conversion for the DORN caffemodel. But this is a [jupyter notebook](https://gist.github.com/likesum/4876bcc776e87ad0e678d84d3c473e54) I used which might be helpful to you. It's not cleaned, and I can't promise if it will work.

Training shouldn't take too long since we use a pre-trained model.

**Comment by anupamsobti** [comment]
Thanks a lot. I'll confirm if this is working.
